name: Test
on:
  push

jobs:
  build:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: swift build
      - name: Run Swift test
        run: swift test
