name: Format
on:
  pull_request:
    paths:
      - "**/*.swift"
      - ".github/workflows/validate-format.yml"

jobs:
  format:
    name: Validate Swift formatting
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - run: swiftformat --lint --reporter github-actions-log .
